# Generated by Django 4.2.6 on 2023-10-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_carts_ip_carts_price_carts_product_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='label',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carts',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='carts',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='static/Products'),
        ),
    ]
